var ParkingConstants = {
  LOAD_CURRENT_PARKING: "LOAD_CURRENT_PARKING",
  LOAD_CURRENT_PARKING_SUCCESS: "LOAD_CURRENT_PARKING_SUCCESS",
  LOAD_CURRENT_PARKING_FAIL: "LOAD_CURRENT_PARKING_FAIL",

  UNSELECT_CURRENT_PARKING: "UNSELECT_CURRENT_PARKING",

  LOAD_PARKING_LIST: "LOAD_PARKING_LIST",
  LOAD_PARKING_LIST_SUCCESS: "LOAD_PARKING_LIST_SUCCESS",
  LOAD_PARKING_LIST_FAIL: "LOAD_PARKING_LIST_FAIL",

  EDIT_LOCATION: "EDIT_LOCATION",
  EDIT_LOCATION_DONE: "EDIT_LOCATION_DONE",
  EDIT_LOCATION_CANCEL: "EDIT_LOCATION_CANCEL",

  CHANGE_CURRENT_PARKING_TEMPORARY_POSITION: "CHANGE_CURRENT_PARKING_TEMPORARY_POSITION",

  NEW_PARKING: "NEW_PARKING",

  NEW_PARKING_UPDATE_DATA: "NEW_PARKING_UPDATE_DATA",

  SAVE_NEW_PARKING: "SAVE_NEW_PARKING",
  SAVE_NEW_PARKING_SUCCESS: "SAVE_NEW_PARKING_SUCCESS",
  SAVE_NEW_PARKING_FAIL: "SAVE_NEW_PARKING_FAIL",

  PARKING_SCROLLED: "PARKING_SCROLLED",

  LOAD_ADDRESS: "LOAD_ADDRESS",
  LOAD_ADDRESS_SUCCESS: "LOAD_ADDRESS_SUCCESS",
  LOAD_ADDRESS_FAIL: "LOAD_ADDRESS_FAIL"

};

module.exports = ParkingConstants;
