var ParkingConstants = {
  LOAD_CURRENT_PARKING: "LOAD_CURRENT_PARKING",
  LOAD_CURRENT_PARKING_SUCCESS: "LOAD_CURRENT_PARKING_SUCCESS",
  LOAD_CURRENT_PARKING_FAIL: "LOAD_CURRENT_PARKING_FAIL",

  UNSELECT_CURRENT_PARKING: "UNSELECT_CURRENT_PARKING",

  LOAD_PARKING_LIST: "LOAD_PARKING_LIST",
  LOAD_PARKING_LIST_SUCCESS: "LOAD_PARKING_LIST_SUCCESS",
  LOAD_PARKING_LIST_FAIL: "LOAD_PARKING_LIST_FAIL"
};

module.exports = ParkingConstants;