var CommentConstants = {
    LOAD_COMMENT_LIST: "LOAD_COMMENT_LIST",
    LOAD_COMMENT_LIST_SUCCESS: "LOAD_COMMENT_LIST_SUCCESS",
    LOAD_COMMENT_LIST_FAIL: "LOAD_COMMENT_LIST_FAIL",

    POST_COMMENT: "POST_COMMENT",
    POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
    POST_COMMENT_FAIL: "POST_COMMENT_FAIL",

    DELETE_COMMENT: "DELETE_COMMENT",
    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL"
};

module.exports = CommentConstants;