var OpinionConstants = {
  LOAD_OPINIONS: "LOAD_OPINIONS",
  LOAD_OPINIONS_SUCCESS: "LOAD_OPINIONS_SUCCESS",
  LOAD_OPINIONS_FAIL: "LOAD_OPINIONS_FAIL",

  POST_OPINION: "POST_OPINION",
  POST_OPINION_SUCCESS: "POST_OPINION_SUCCESS",
  POST_OPINION_FAIL: "POST_OPINION_FAIL",

  POST_LOCATION: "POST_LOCATION",
  POST_LOCATION_SUCCESS: "POST_LOCATION_SUCCESS",
  POST_LOCATION_FAIL: "POST_LOCATION_FAIL",

  EDIT_OPINION: "EDIT_OPINION"
};

module.exports = OpinionConstants;
