var ParkingImageConstants = {
  LOAD_PARKING_IMAGE_LIST: "LOAD_PARKING_IMAGE_LIST",
  LOAD_PARKING_IMAGE_LIST_SUCCESS: "LOAD_PARKING_IMAGE_LIST_SUCCESS",
  LOAD_PARKING_IMAGE_LIST_FAIL: "LOAD_PARKING_IMAGE_LIST_FAIL",

  POST_PARKING_IMAGE: "POST_PARKING_IMAGE",
  POST_PARKING_IMAGE_SUCCESS: "POST_PARKING_IMAGE_SUCCESS",
  POST_PARKING_IMAGE_FAIL: "POST_PARKING_IMAGE_FAIL",

  DELETE_PARKING_IMAGE: "DELETE_PARKING_IMAGE",
  DELETE_PARKING_IMAGE_SUCCESS: "DELETE_PARKING_IMAGE_SUCCESS",
  DELETE_PARKING_IMAGE_FAIL: "DELETE_PARKING_IMAGE_FAIL",

  SLIDE_PARKING_IMAGE: "SLIDE_PARKING_IMAGE"
};

module.exports = ParkingImageConstants;
